Month12/step1
Gyxer513/algososh pull request #1
Opened 2023-03-07 09:50 UTC by Gyxer513

Здравствуйте!

Направляю работу на ревью.

2023-03-07 12:00 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Была проделана огромная работа 🔥.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализованы все алгоритмы.

### **Но есть несколько замечаний, которые нужно исправить:**

- "Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE;

- По чек-листу: классы, описывающие работу структур данных, должны быть вынесены в отдельные файлы в папке соответствующего компонента.

- Сортировка массива:

  - <https://disk.yandex.com/i/OlA--bp1vL_m5Q> - По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма. А у вас лоадер отображается на двух кнопках (которые выделил), а 3 кнопка остаётся активной.

  - Стоит поправить вёрстку, уменьшите расстояние между блоками, и отцентрируйте.

- Стек:

  - По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма. А у вас лоадер отображается на всех кнопках.

- Очередь:

  - По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма. А у вас лоадер отображается на всех кнопках.

- Связный список:

  - По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма. А у вас лоадер отображается на всех кнопках, которые расположены сверху.

  - У вас не должно быть надписи `Dell`, при удалении элемента их списка - <https://disk.yandex.com/i/SVfFzBbM612u4w>, должно быть так:
    <https://disk.yandex.com/i/DbUsxUz-I1pSUA> - При удалении элемента кружок замещает надпись tail;

  - Если нажать на `Добавить в tail`, то связной список очищается, так быть не должно.

  - При добавлении/удалении элемента по индексу, анимация должна выполнятся поэтапно. Советую ещё раз ознакомится с заданием на проект, там всё описано.
    <https://disk.yandex.com/i/t7C-rdxk175aYQ>

  - При добавлении по индексу, вы должны проверять, "существует" ли такой индекс вообще. <https://disk.yandex.com/i/uVnMGtwLGD216Q>

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален;

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-03-07 12:00 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +    +e.currentTarget.value > 0 && +e.currentTarget.value <= 19
**Надо исправить:**

"Магические" значения лучше вынести в константу.

2023-03-07 12:00 UTC, ArslanDev666 commented on src/utils/fibonacci.ts
> +};
**Надо исправить:**

По чек-листу вы должны реализовать функцию `getFibonacciNumbers`, которая принимает количество чисел как параметр и возвращает требуемый массив чисел последовательности Фибоначчи. Это утилитарная функция, поэтому она должна находится в `utils`, в той же папке, что и алгоритм, т.к. в `fibonacci-page`.

 Просто переименуйте функцию, и перенесите всё в файл в папку со страницей)

2023-03-07 12:00 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          max={19}
**Надо исправить:**

"Магические" значения лучше вынести в константу.

2023-03-07 12:00 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          type={"number"}
**Можно лучше:**

обычные строковые значения, лучше не оборачивать в шаблонные строки.

2023-03-07 12:00 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +    setCurrentElement("DELL");
**Надо исправить:** 

Здесь и далее.

тут должно быть значение из кружка, а не надпись `Dell`

2023-03-07 12:00 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +            maxLength={4}
**Надо исправить:**

"Магические" значения лучше вынести в константу.

2023-03-07 12:00 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +      ...Array.from({ length: 7 }, () => ({
**Надо исправить:**

Здесь и далее.

"Магические" значения лучше вынести в константу.

2023-03-07 12:00 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +                  index === queue.getHead() && !queue.isEmpty() ? "head" : ""
**Можно лучше:**

Тут лучше использовать константы `head` и `tail`, они у вас находятся в папке `constants`.

2023-03-07 12:00 UTC, ArslanDev666 commented on src/components/stack-page/stack-page.tsx
> +          maxLength={4}
**Надо исправить:**

"Магические" значения лучше вынести в константу.

2023-03-07 16:54 UTC, Gyxer513 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +    +e.currentTarget.value > 0 && +e.currentTarget.value <= 19
Исправлено.

2023-03-07 16:55 UTC, Gyxer513 commented on src/utils/fibonacci.ts
> +};
Исправлено.

2023-03-07 16:56 UTC, Gyxer513 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          max={19}
Исправлено.

2023-03-07 16:57 UTC, Gyxer513 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          type={"number"}
Исправлено.

2023-03-07 17:10 UTC, Gyxer513 commented on src/components/list-page/list-page.tsx
> +    setCurrentElement("DELL");
Исправлено.

2023-03-07 17:13 UTC, Gyxer513 commented on src/components/list-page/list-page.tsx
> +            maxLength={4}
Исправлено.

2023-03-07 17:17 UTC, Gyxer513 commented on src/components/queue-page/queue-page.tsx
> +      ...Array.from({ length: 7 }, () => ({
Исправлено.

2023-03-07 17:21 UTC, Gyxer513 commented on src/components/queue-page/queue-page.tsx
> +                  index === queue.getHead() && !queue.isEmpty() ? "head" : ""
Исправлено.

2023-03-07 17:56 UTC, Gyxer513 commented on src/components/stack-page/stack-page.tsx
> +          maxLength={4}
Исправлено.

2023-03-07 19:25 UTC, Gyxer513 commented
**Сортировка массива:** 

Блок соответствует заданию, исправлена верстка. 


**Стек:**

Блок соответствует заданию. 

**Очередь:**

Блок соответствует заданию. 

**Связный список:**


Блок соответствует заданию.

2023-03-08 01:54 UTC, Gyxer513 commented
Исправлена анимация в списке.

2023-03-08 07:56 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но есть несколько замечаний, которые нужно исправить:**

- По чек-листу: классы, описывающие работу структур данных и утилиты, должны быть вынесены в отдельные файлы в папке соответствующего компонента. Т.е. они должны находится возле своих страниц, просто в отдельном файле. <https://disk.yandex.com/i/SDVUNp_VA0_XQQ> - вот в таких файлах. Тоже самое касается и классов;

- Связный список:

  - Если нажать на `Удалить из head`, то иногда (когда мало элементов) не срабатывает анимация удаления. <https://disk.yandex.com/i/ey4B2iJbmi1vdQ>;

  - При удалении элемента, кружок должен быть пустым: <https://disk.yandex.com/i/z0iyCnrmuMRm1Q>;

  - При удалении элемента по индексу, анимация должна выполнятся поэтапно. Советую ещё раз ознакомится с заданием на проект, там всё описано.
    <https://disk.yandex.com/i/wLHi1HEVh-ZZGQ>

### **Сделает код лучше:**

- лучше всегда использовать строгое сравнение `===` и строгое неравентсво `!==`;

2023-03-08 10:29 UTC, Gyxer513 commented
Добрый день!

Все замечания исправлены.

2023-03-08 15:49 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-03-09 08:11 UTC, merged